services:

  mcp-files-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9096:6060
    environment:
      - MCP_HTTP_PORT=6060
      - LOCAL_WORKSPACE_FOLDER=/app/workspace
    volumes:
      - ./workspace:/app/workspace



